# Generated by Django 4.2 on 2023-05-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_reserva_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="categoria",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="reserva",
            name="isFinalizado",
            field=models.BooleanField(default=False),
        ),
    ]
