# Generated by Django 4.2 on 2023-06-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_reserva_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="categoria",
            field=models.CharField(
                choices=[("Gato", "Gato"), ("Cachorro", "Cachorro")],
                max_length=30,
                verbose_name="Categoria",
            ),
        ),
    ]
