# Generated by Django 4.2 on 2023-06-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_reserva_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reserva",
            name="horario",
            field=models.CharField(
                choices=[
                    ("07:00", "07:00"),
                    ("08:00", "08:00"),
                    ("09:00", "09:00"),
                    ("10:00", "10:00"),
                    ("11:00", "11:00"),
                    ("13:00", "13:00"),
                    ("14:00", "14:00"),
                    ("15:00", "15:00"),
                    ("16:00", "16:00"),
                    ("17:00", "17:00"),
                ],
                max_length=5,
                verbose_name="Horário",
            ),
        ),
    ]
