# Generated by Django 4.2 on 2023-06-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_contato_options_alter_reserva_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="tamanho",
            field=models.IntegerField(
                choices=[(0, "Pequeno"), (1, "Médio"), (2, "Grande")],
                default=0,
                verbose_name="Tamanho",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reserva",
            name="isFinalizado",
            field=models.BooleanField(default=False, verbose_name="Serviço Finalizado"),
        ),
    ]
