# Generated by Django 4.2.2 on 2023-07-11 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_categoria_reserva_categoria_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='categoria_pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='core.categoria'),
        ),
    ]
