# Generated by Django 4.2.2 on 2023-07-11 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_reserva_categoria_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='categoria',
        ),
    ]
